// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-enable'
  | 'pref-help'
  | 'pref-mcp-copy-claude-code'
  | 'pref-mcp-copy-claude-desktop'
  | 'pref-mcp-copy-token'
  | 'pref-mcp-description'
  | 'pref-mcp-enable'
  | 'pref-mcp-port'
  | 'pref-mcp-status'
  | 'pref-mcp-title'
  | 'pref-title'
  | 'prefs-title';
