import { config } from "../../package.json";

/** Generated by zotero-plugin-scaffold from addon/prefs.js (typings/prefs.d.ts). */
type PluginPrefsMap = _ZoteroTypes.Prefs["PluginPrefsMap"];

/** Typed read of a plugin preference (defaults come from addon/prefs.js). */
export function getPref<K extends keyof PluginPrefsMap>(
  key: K,
): PluginPrefsMap[K] {
  return Zotero.Prefs.get(
    `${config.prefsPrefix}.${key}`,
    true,
  ) as PluginPrefsMap[K];
}

export function setPref<K extends keyof PluginPrefsMap>(
  key: K,
  value: PluginPrefsMap[K],
): void {
  Zotero.Prefs.set(`${config.prefsPrefix}.${key}`, value, true);
}
